  name: rsloader
  version: '1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: rsloader is a lightweight loader for the RuneScape game.
  description: |
    Rsloader is a lightweight loader for the RuneScape game.
    Its aim is to replicate the functionality of jagexappletviewer.jar, 
    but as free and open-source software (FOSS).

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    rsloader:
      command: java -jar $SNAP/usr/bin/rsloader.jar -o

      plugs: 
        - network
        - network-bind
        - home
        - x11
        - pulseaudio
        - gsettings
        - alsa
     
  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: ant
      source-type: git
      source: https://github.com/ShivamMistry/RSLoader.git
      stage-packages:
        - openjdk-8-jre
        
     install: |
      mkdir -p  ../../../prime/usr/bin
      cp -r out/* ../../../prime/usr/bin
    
